import GeometricSiphon.Defs
import GeometricSiphon.GeometricResidual
import GeometricSiphon.Monotonicity
import GeometricSiphon.DirectionalExit
import GeometricSiphon.Extinction
import GeometricSiphon.Convergence
import GeometricSiphon.ConvergenceDiscrete
